apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gigmatch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/fred4impact/mern-gigmatch.git'
    targetRevision: feature-dev
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gigmatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10