version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: gigmatch-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: gigmatch-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gigmatch
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key-here
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    working_dir: /usr/src/app

  frontend:
    build: ./frontend
    container_name: gigmatch-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
