apiVersion: v1
kind: ConfigMap
metadata:
  name: gigmatch-config
  namespace: gigmatch
data:
  NODE_ENV: production
  FRONTEND_URL: https://gigmatch.yourdomain.com
  PORT: "5000"
  REACT_APP_API_URL: "https://api.gigmatch.yourdomain.com/api" 