apiVersion: v1
kind: ConfigMap
metadata:
  name: gigmatch-config
  namespace: gigmatch
data:
  NODE_ENV: staging
  FRONTEND_URL: https://staging.gigmatch.yourdomain.com
  PORT: "5000"
  REACT_APP_API_URL: "https://staging-api.gigmatch.yourdomain.com/api" 