apiVersion: v1
kind: ConfigMap
metadata:
  name: gigmatch-config
  namespace: gigmatch
data:
  NODE_ENV: development
  FRONTEND_URL: http://localhost:3000
  PORT: "5000"
  REACT_APP_API_URL: "http://localhost:5000/api"