{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gigmatch-monitoring.prometheusConfigName" . }}
  namespace: {{ .Values.global.namespaceOverride | default "monitoring" }}
  labels:
    {{- include "gigmatch-monitoring.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.prometheus.config.global.evaluation_interval }}

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      {{- range .Values.prometheus.config.scrape_configs }}
      - job_name: '{{ .job_name }}'
        {{- if .static_configs }}
        static_configs:
          {{- range .static_configs }}
          - targets: {{ toYaml .targets | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
          {{- range .kubernetes_sd_configs }}
          - role: {{ .role }}
          {{- end }}
        {{- end }}
        {{- if .scheme }}
        scheme: {{ .scheme }}
        {{- end }}
        {{- if .tls_config }}
        tls_config:
          {{- toYaml .tls_config | nindent 10 }}
        {{- end }}
        {{- if .bearer_token_file }}
        bearer_token_file: {{ .bearer_token_file }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
          {{- range .relabel_configs }}
          - {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .scrape_interval }}
        scrape_interval: {{ .scrape_interval }}
        {{- end }}
        {{- if .metrics_path }}
        metrics_path: {{ .metrics_path }}
        {{- end }}
      {{- end }}
{{- end }} 