name: CI/CD Pipeline

on:
  push:
    branches: [main, feature-*]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports: [27017:27017]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend dependencies
        run: cd backend && npm ci
      - name: Install frontend dependencies
        run: cd frontend && npm ci
      - name: Run backend tests
        run: cd backend && npm test
        env:
          JWT_SECRET: testsecret
      - name: Security scan backend
        run: cd backend && npm audit --audit-level=high || true
      - name: Security scan frontend
        run: cd frontend && npm audit --audit-level=high || true
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gigmatch-backend:latest ./backend
      - name: Scan backend Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/gigmatch-backend:latest
          severity: "HIGH,CRITICAL"
      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gigmatch-frontend:latest ./frontend
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gigmatch-backend:latest
      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gigmatch-frontend:latest
